### PR TITLE
fix #14: text is editable keyboard-only in Chrome too

### LINKED ISSUE #14: editing text keyboard-only not working in chrome (demo)
# Problem/Need:

can't edit text if i only use keyboard in chrome (works in firefox)

# Tried:

https://codepen.io/hchiam/full/pobxgBo

and locally with `yarn demo`

# Suggestions:

js .focus() when contenteditable?

### PR DESCRIPTION
**Pull request by hchiam**
# Problem/Need:

fix #14

# Suggested changes:

setCaret

https://developer.mozilla.org/en-US/docs/Web/API/Selection/addRange

### CODE REVIEW

File: makeElementDraggableAndEditable.js [hunk 1]
```diff
@@ -202,6 +202,9 @@ function makeElementDraggableAndEditable(element, settings) {
           element.detectAsClickToEdit = false;
           element.contentEditable = false;
         } else if (!isTabKey(event)) {
+          if (!element.startedTyping) {
+            setCaret(element);
+          }
```
Comment (hchiam) [inline makeElementDraggableAndEditable.js:207]: need the if statement so the caret doesn't get stuck

**Review by hchiam — COMMENTED** [review]
LGTM! :+1:
